### Create a new poll
POST http://localhost:3000/api/v1/polls
Content-Type: application/json

{
   "question": "Which programming language do you prefer for backend development?",
   "options": ["Node.js", "Python", "Java", "Go"]
}

### Get all polls
GET http://localhost:3000/api/v1/polls

### Get a single poll
GET http://localhost:3000/api/v1/polls/68a59e21c374ad5a30d227ff

### Vote on Poll
POST http://localhost:3000/api/v1/votes
Content-Type: application/json

{
  "pollId": "PASTE_VALID_ID_HERE",
  "option": "react",
  "voter": "narda@example.com"
}

### View results for a poll
GET http://localhost:3000/api/v1/votes/PASTE_VALID_ID_HERE
